# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_selectcard.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_selectcard(object):
    def setupUi(self, selectcard):
        selectcard.setObjectName("selectcard")
        selectcard.resize(727, 1018)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("cute.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        selectcard.setWindowIcon(icon)
        self.sel_card_list = QtWidgets.QTableWidget(selectcard)
        self.sel_card_list.setGeometry(QtCore.QRect(10, 60, 700, 951))
        self.sel_card_list.setAutoFillBackground(True)
        self.sel_card_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.sel_card_list.setAlternatingRowColors(True)
        self.sel_card_list.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.sel_card_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.sel_card_list.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.sel_card_list.setRowCount(0)
        self.sel_card_list.setColumnCount(4)
        self.sel_card_list.setObjectName("sel_card_list")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.sel_card_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.sel_card_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.sel_card_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.sel_card_list.setHorizontalHeaderItem(3, item)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(selectcard)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(480, 10, 235, 41))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ok_sel_card = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.ok_sel_card.setObjectName("ok_sel_card")
        self.gridLayout_2.addWidget(self.ok_sel_card, 0, 0, 1, 1)
        self.cancel_sel_card = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.cancel_sel_card.setObjectName("cancel_sel_card")
        self.gridLayout_2.addWidget(self.cancel_sel_card, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(selectcard)
        self.label.setGeometry(QtCore.QRect(370, 15, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.num_sel_card = QtWidgets.QLineEdit(selectcard)
        self.num_sel_card.setGeometry(QtCore.QRect(420, 15, 50, 30))
        self.num_sel_card.setObjectName("num_sel_card")
        self.type_sel_card = QtWidgets.QComboBox(selectcard)
        self.type_sel_card.setGeometry(QtCore.QRect(190, 15, 150, 30))
        self.type_sel_card.setObjectName("type_sel_card")
        self.color_sel_card = QtWidgets.QComboBox(selectcard)
        self.color_sel_card.setGeometry(QtCore.QRect(10, 15, 150, 30))
        self.color_sel_card.setObjectName("color_sel_card")
        self.color_sel_card.addItem("")
        self.color_sel_card.addItem("")
        self.color_sel_card.addItem("")
        self.color_sel_card.addItem("")
        self.color_sel_card.addItem("")
        self.color_sel_card.addItem("")

        self.retranslateUi(selectcard)
        QtCore.QMetaObject.connectSlotsByName(selectcard)

    def retranslateUi(self, selectcard):
        _translate = QtCore.QCoreApplication.translate
        selectcard.setWindowTitle(_translate("selectcard", "选择卡片"))
        item = self.sel_card_list.horizontalHeaderItem(0)
        item.setText(_translate("selectcard", "Card ID"))
        item = self.sel_card_list.horizontalHeaderItem(1)
        item.setText(_translate("selectcard", "lv."))
        item = self.sel_card_list.horizontalHeaderItem(2)
        item.setText(_translate("selectcard", "Card Name"))
        item = self.sel_card_list.horizontalHeaderItem(3)
        item.setText(_translate("selectcard", "description"))
        self.ok_sel_card.setText(_translate("selectcard", "确定"))
        self.cancel_sel_card.setText(_translate("selectcard", "取消"))
        self.label.setText(_translate("selectcard", "Num:"))
        self.color_sel_card.setItemText(0, _translate("selectcard", "ALL"))
        self.color_sel_card.setItemText(1, _translate("selectcard", "red"))
        self.color_sel_card.setItemText(2, _translate("selectcard", "blue"))
        self.color_sel_card.setItemText(3, _translate("selectcard", "green"))
        self.color_sel_card.setItemText(4, _translate("selectcard", "colorless"))
        self.color_sel_card.setItemText(5, _translate("selectcard", "curse"))

